!!python/object:Solstice.AppConfig
  new_loan_limit: 100
  profitability: 20
  concentration: 20
  profitability_p: 20
  concentration_p: 20
  portfolio_size: 12
  duration: 300
  time_delta: 0.03
  winning_score: 500